// Generated by LiveScript 1.5.0
(function(){
  var GitHub, marked, p, maybe, cmsless, slice$ = [].slice;
  GitHub = require('github-api');
  marked = require('marked');
  p = require('prelude-ls');
  maybe = curry$(function(def, val){
    return val != null ? val : def;
  });
  cmsless = function(config){
    var github, load;
    github = new GitHub({
      username: config.github.username,
      password: config.github.password,
      auth: 'basic'
    });
    load = curry$(function(gists, callback){
      var head, tail;
      head = gists[0], tail = slice$.call(gists, 1);
      if (head == null) {
        return callback(null, []);
      }
      return github.getGist(head.id).read(function(err, gistContent){
        var getContent, result;
        if (err != null) {
          return callback(err);
        }
        getContent = function(fileconfig){
          var parts, ext, transform, content, transformed;
          parts = p.map(function(it){
            return it.trim();
          })(
          p.split(">")(
          fileconfig));
          ext = parts[0].match(/[^.]+$/i);
          transform = function(content){
            switch (false) {
            case !(parts[1] === 'html' && ext === 'md'):
              return marked(content);
            case ext !== 'json':
              return JSON.parse(content);
            default:
              return content;
            }
          };
          content = gistContent.files[parts[0]].content;
          transformed = content != null ? transform(content) : "";
          return [parts[0], content];
        };
        result = p.pairsToObj(
        p.map(getContent)(
        head.files));
        load(tail, function(err, child){
          var collected;
          if (err != null) {
            return callback(err);
          }
          collected = [result].concat(child);
          callback(null, collected);
        });
      });
    });
    return {
      load: load(config.gists)
    };
  };
  module.exports = cmsless;
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
