// Generated by LiveScript 1.5.0
(function(){
  var GitHub, marked, p, cmsless, list, createGist, config;
  GitHub = require('github-api');
  marked = require('marked');
  p = require('prelude-ls');
  cmsless = require("../index.js");
  list = ['e4784c834af0ec6bedb2f47614b54bec', '967bac6b366f292d47f9777ca0d2bf83', '57ffb4bf954b70341f26e5079ff95ecd'];
  createGist = function(id){
    return {
      id: id,
      files: ["info.json", "about.md > html"]
    };
  };
  config = {
    github: {
      username: 'askucher',
      password: "vtufgjkbc1"
    },
    gists: p.map(createGist)(
    list)
  };
  cmsless(config).load(function(err, items){
    console.log(err, items);
  });
}).call(this);
